content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    view:
      fields: [title, tags, date]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc