content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    view:
      fields: [title, tags, date]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text